### ISSUE TITLE
Crash when doing "Check for duplicates" on Arcticons

### ISSUE THREAD

**Issue by quantenzitrone** [Kaiserdragon2/IconRequest#15]
## Scoop

```
FATAL EXCEPTION: main
Process: de.kaiserdragon.iconrequest, PID: 10316
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at de.kaiserdragon.iconrequest.RequestActivity.d0(Unknown Source:121)
	at de.kaiserdragon.iconrequest.RequestActivity.h0(Unknown Source:26)
	at de.kaiserdragon.iconrequest.RequestActivity.O(Unknown Source:0)
	at k1.j.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

I can't reproduce this tho. Maybe it helps anyways.

**Comment by quantenzitrone** [comment]
i thought i reproduced but its a different error:
```
FATAL EXCEPTION: main
Process: de.kaiserdragon.iconrequest, PID: 10482
java.lang.NullPointerException: Attempt to read from field 'android.graphics.drawable.Drawable de.kaiserdragon.iconrequest.a.a' on a null object reference
	at de.kaiserdragon.iconrequest.RequestActivity.d0(Unknown Source:181)
	at de.kaiserdragon.iconrequest.RequestActivity.h0(Unknown Source:26)
	at de.kaiserdragon.iconrequest.RequestActivity.O(Unknown Source:0)
	at k1.j.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

**Comment by Kaiserdragon2** [comment]
The only crash I am able to produce is by touching on the screen while the loading is displayed. This seems to happen because the app doesn't respond to the touch event. But i can't produce the errors above do they also happen during loading?

**Comment by quantenzitrone** [comment]
the second error happened when checking for missing icons, and both while loading yes

when i touch the screen while it loads, as you described, no crash happens tho

**Comment by quantenzitrone** [comment]
oh, i just got the first crash again

**Comment by quantenzitrone** [comment]
weird, why would it sometimes crash but other times not, i don't think i did anything different

**Comment by Kaiserdragon2** [comment]
I have changed some things but i am not sure if these crashes are related but you could test it with the new release
